// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCfLE33gh2FRTSDN4OdkVGPHTntNKs7Sw',
    appId: '1:996811055049:web:9bf167e4836709b4f75218',
    messagingSenderId: '996811055049',
    projectId: 'shuttlelink-373c9',
    authDomain: 'shuttlelink-373c9.firebaseapp.com',
    storageBucket: 'shuttlelink-373c9.firebasestorage.app',
    databaseURL: 'https://shuttlelink-373c9-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKyFnSElGLHE4L_t401k7jPZblHDrl8WY',
    appId: '1:996811055049:android:f0e760586cfc0693f75218',
    messagingSenderId: '996811055049',
    projectId: 'shuttlelink-373c9',
    storageBucket: 'shuttlelink-373c9.firebasestorage.app',
    databaseURL: 'https://shuttlelink-373c9-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu7oJaxhactWw2P6pBqgaP2PTmHOz9j3A',
    appId: '1:996811055049:ios:426a72085360b384f75218',
    messagingSenderId: '996811055049',
    projectId: 'shuttlelink-373c9',
    storageBucket: 'shuttlelink-373c9.firebasestorage.app',
    iosBundleId: 'com.example.shuttlelinkApp',
    databaseURL: 'https://shuttlelink-373c9-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu7oJaxhactWw2P6pBqgaP2PTmHOz9j3A',
    appId: '1:996811055049:ios:426a72085360b384f75218',
    messagingSenderId: '996811055049',
    projectId: 'shuttlelink-373c9',
    storageBucket: 'shuttlelink-373c9.firebasestorage.app',
    iosBundleId: 'com.example.shuttlelinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCfLE33gh2FRTSDN4OdkVGPHTntNKs7Sw',
    appId: '1:996811055049:web:ec83ba46c4c67d47f75218',
    messagingSenderId: '996811055049',
    projectId: 'shuttlelink-373c9',
    authDomain: 'shuttlelink-373c9.firebaseapp.com',
    storageBucket: 'shuttlelink-373c9.firebasestorage.app',
    databaseURL: 'https://shuttlelink-373c9-default-rtdb.firebaseio.com',
  );
}
